### PR TITLE
clean up basemodui by removing p2 coop, l4d2 Xbox ui, tf2 scoreboard and hl2 strings

### PR DESCRIPTION
**Pull request by pivotman319-new**
Shaved off 217 kilobytes' worth of unused basemodui strings.

I may have accidentally removed some used ingame strings (coop I think) in the process but it's probably not going to matter in this case. Do let me know if there are issues with this PR.

### CODE REVIEW

**Comment by Krzyhau** [comment]
A bunch of main menu strings is missing.

**Comment by pivotman319-new** [comment]
@Krzyhau please check the latest commits, thanks

**Comment by Krzyhau** [comment]
Seems fine to me.

**Comment by pivotman319-new** [comment]
> Seems fine to me.

Thanks :)

**Pull request merged**
